import Head from "next/head";
import LandingPage from "../src/components/landingPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>what-happen | dev</title>
        <meta name="description" content="Generated by nomercybros" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LandingPage />
    </>
  );
}
