import Head from "next/head";
import styled from "styled-components";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Wrapper>
        <span>영준님 안녕하세요~ 오늘 무슨 회의 할까요?</span>
        <span>영준님 안녕하세요~ 오늘 무슨 회의 할까요?</span>
        <span>영준님 안녕하세요~ 오늘 무슨 회의 할까요?</span>
      </Wrapper>
    </div>
  );
}

const Wrapper = styled("div")`
  background-color: ${({ theme }) => theme.bg.primary};
  color: ${({ theme }) => theme.text.primary};
  @media ${({ theme }) => theme.device.laptop} {
    display: flex;
    flex-direction: column;
  }
`;
